### PR TITLE
cherry-pick: API BREAK: use unsigned types for 1-bit fields of 'obj_state_s'

### LINKED ISSUE #80: Build warnings of [-Wsingle-bit-bitfield-constant-conversion] from outdated GraphViz library
# Environment details

Go version
```
$ go version
go version go1.21.1 darwin/arm64
```

C Compiler
```
$ go env
...
CC='clang'
...

$ clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
...
```

# Issue
When building the example code in the repository's readme with `go build`, I see the following compiler warnings from `clang`:
```
# github.com/goccy/go-graphviz/internal/ccall
In file included from common.c:5:
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:165:35: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2540:24: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2596:35: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2602:35: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2612:31: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2623:31: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2628:31: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2641:28: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2650:33: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2659:32: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
../../../../go/modcache/github.com/goccy/go-graphviz@v0.1.2/internal/ccall/common/emit.c:2668:32: warning: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Wsingle-bit-bitfield-constant-conversion]
```

Note that this is a separate issue from #72 and is *not* fixed by #77.

These come from the bundled GraphViz library assigning a literal `1` to *signed* int bitfields of an `obj_state_t`. This issue was resolved in GraphViz 3.0.0 released on 2022-02-26. The specific commit with the fix is [96f9d101](https://gitlab.com/graphviz/graphviz/-/commit/96f9d101d336c50521d1c21a0e228497298f985d), which simply changes the relevant bitfields to *unsigned* ints. These bitfields are present in go-graphviz here: https://github.com/goccy/go-graphviz/blob/9f8e121468ccc62068d524bc26f4429194ba0218/internal/ccall/gvc/gvcjob.h#L235-L244

This issue can be resolved extremely easily by replacing the `int` keyword with `unsigned` (alias for `unsigned int`) in the above code, just as the GraphViz developers did. However, I would like to push for #42 to be finished and the bundled libraries (including GraphViz and Expat) to be updated to more recent versions. Updating the bundled dependencies would close out several other issues in this repository, like #47. More pressingly, bundling outdated libraries poses a security risk, as evidenced by the Expat CVEs mentioned in #76.

Please let me know if you would like me to submit a PR for the specific issue of the bitfield warnings. In the meantime, can you provide a timeline on when the bundled libraries might be able to be updated? Thank you.

### PR DESCRIPTION
**Pull request by edaniels**
Fixes #80 

@thomasfleming-cs, probably still better to update the vendored library all together but this is tiny to start

### CODE REVIEW

**Comment by edaniels** [comment]
@goccy just bumping for your attention. Thank you for your work!

**Comment by gedw99** [comment]
thanks @edaniels 

can confirm this fixed things for me. 

```sh
rm -rf go-graphviz
git clone https://github.com/edaniels/go-graphviz -b bitfield_proper_set
@echo go-graphviz >> .gitignore
touch go.work
go work use go-graphviz
cd go-graphviz/cmd/dot && go build . 

```

**Comment by goccy** [comment]
@edaniels Sorry for late reply. Looks good to me this changes, but I couldn't confirm any CI logs, so please push empty commit and re-run CI.

**Comment by edaniels** [comment]
@goccy done. Looks like it needs your approval to start.

**Comment by goccy** [comment]
Thank you for your contribution ! Merged.

**Pull request merged**
